apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: dispatch
spec:
  rules:
    - matches:
      - headers:
          - type: Exact
            name: to
            value: left
      backendRefs:
      - name: left
        port: 80
    - backendRefs:
      - name: right
        port: 80
