apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: left
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /left
      backendRefs:
      - name: left
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: right
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /right
      backendRefs:
      - name: right
        port: 80
