ingressPublishService: "ingress-apisix/apisix"
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
gateway:
  type: NodePort
  http:
    nodePort: "30800"
