ingressPublishService: "ingress-apisix/apisix"
ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: ingress-apisix
    image:
      tag: "1.6.1"
    kubernetes:
      enableGatewayAPI: true
gateway:
  type: NodePort
  http:
    nodePort: "30800"
