ingress-controller:
  enabled: true
  config:
    ingressPublishService: "ingress-apisix/apisix-gateway"
    kubernetes:
      enableGatewayAPI: true
gateway:
  type: NodePort
  http:
    nodePort: 30800
